reversescore transcribe data/wav/angelica_bjbn5mice4k.wav \
  --demucs-model htdemucs_6s \
  --bandoneon \
  --violin \
  --piano \
  --bass \
  --voice \
  --no-guitar \
  --no-drums \
  --time-signature 3/4 \
  --grid 4
